#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

banner "top-des-tops → Vercel : provisioning de la copie de test"

# ── Stage 1: CLI Vercel + connexion + lien de projet ──────────────────────
stage "CLI Vercel : installation, connexion, lien de projet"
say "On installe la CLI Vercel si besoin, puis on connecte ce dossier à un projet Vercel."
if ! command -v vercel >/dev/null 2>&1; then
  step "Installation de la CLI Vercel (npm i -g vercel)..."
  npm i -g vercel
else
  note "CLI Vercel déjà installée ($(vercel --version))."
fi
step "Connexion à ton compte Vercel (vercel login) — suis les instructions à l'écran."
vercel login
step "Lien de ce dossier à un projet Vercel (vercel link) — si on te demande un nom de nouveau projet, propose : top-des-tops-vercel."
vercel link

# ── Stage 2: Projet Google Cloud + compte de service ───────────────────────
stage "Google Cloud : projet + compte de service"
say "On crée (ou réutilise) un projet Google Cloud, on active l'API Sheets, puis on crée un compte de service avec une clé JSON."
open_url "https://console.cloud.google.com/projectcreate"
step "Crée un nouveau projet (ou choisis-en un existant dans le sélecteur en haut) — note son ID (ex: top-des-tops-bridge)."
ask GCP_PROJECT_ID "ID du projet Google Cloud utilisé :"
open_url "https://console.cloud.google.com/apis/library/sheets.googleapis.com?project=${GCP_PROJECT_ID}"
step "Clique sur 'Activer' pour activer Google Sheets API sur ce projet (si ce n'est pas déjà fait)."
pause "Une fois l'API activée, appuie sur Entrée."
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create?project=${GCP_PROJECT_ID}"
step "Crée un compte de service (nom libre, ex: top-des-tops-sheets-reader). Pas besoin de rôle IAM au niveau du projet — l'accès au Sheet se fait par partage direct (étape suivante)."
step "Une fois créé, ouvre-le dans la liste > onglet 'Clés' (Keys) > Ajouter une clé > Créer une clé > format JSON. Le fichier se télécharge automatiquement."
ask GCP_SA_EMAIL "Colle l'adresse email du compte de service (finit par .iam.gserviceaccount.com) :"
ask GCP_SA_KEY_PATH "Chemin complet vers le fichier JSON téléchargé :"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_SA_EMAIL "$GCP_SA_EMAIL"
note "Le chemin de la clé n'est pas écrit dans .env (il pointe vers un fichier secret) — retenu seulement pour cette session."

# ── Stage 3: Partage du Sheet de test ───────────────────────────────────────
stage "Partage du Google Sheet de test"
say "Le compte de service doit avoir accès en lecture au Sheet de test — sans ça, toute lecture échouera en 403."
open_url "https://docs.google.com/spreadsheets/d/1IpnM_k7sicaktxtvwaYMiMnFbnJz6nhsELmagF1WS78/edit"
step "Bouton 'Partager' (en haut à droite) > colle l'adresse : ${GCP_SA_EMAIL} > rôle 'Lecteur' > Envoyer."
note "Lecteur suffit : ce plan (1/6) est en lecture seule (scope OAuth spreadsheets.readonly)."
note "L'élévation à Éditeur se fera explicitement au Plan 2, quand des écritures seront introduites."
confirm "Le Sheet est bien partagé avec ${GCP_SA_EMAIL} en rôle Lecteur ?" || warn "Sans ce partage, /api/health répondra 403 — reviens à cette étape avant de continuer."

# ── Stage 4: Variable d'environnement Vercel ────────────────────────────────
stage "Variable d'environnement Vercel : GOOGLE_SERVICE_ACCOUNT_KEY"
say "On envoie le contenu du fichier JSON (une seule ligne) comme variable d'environnement Vercel — jamais commitée dans le repo."
if [[ -f "$GCP_SA_KEY_PATH" ]]; then
  SA_KEY_CONTENT=$(tr -d '\n' < "$GCP_SA_KEY_PATH")
  step "Envoi vers Vercel (vercel env add GOOGLE_SERVICE_ACCOUNT_KEY production)..."
  printf '%s' "$SA_KEY_CONTENT" | vercel env add GOOGLE_SERVICE_ACCOUNT_KEY production
  note "✓ Variable envoyée. Le contenu de la clé n'a été écrit dans aucun fichier de ce repo."
else
  warn "Fichier introuvable à ce chemin : ${GCP_SA_KEY_PATH}"
  step "Configure la variable à la main : Vercel dashboard > ton projet > Settings > Environment Variables > GOOGLE_SERVICE_ACCOUNT_KEY (colle le JSON complet en une ligne) > Production."
  SKIPPED+=("Variable Vercel GOOGLE_SERVICE_ACCOUNT_KEY (fichier de clé introuvable à ${GCP_SA_KEY_PATH} — à faire à la main)")
fi

# ── Stage 5: Premier déploiement ────────────────────────────────────────────
stage "Premier déploiement"
say "On déploie en production pour obtenir une vraie URL Vercel."
DEPLOY_LOG=$(mktemp)
vercel --prod 2>&1 | tee "$DEPLOY_LOG"
DEPLOY_URL=$(grep -Eo 'https://[a-zA-Z0-9.-]+\.vercel\.app' "$DEPLOY_LOG" | tail -n1 || true)
rm -f "$DEPLOY_LOG"
if [[ -z "$DEPLOY_URL" ]]; then
  ask DEPLOY_URL "Je n'ai pas trouvé l'URL automatiquement dans la sortie ci-dessus — colle l'URL de déploiement affichée :"
else
  note "URL détectée : ${DEPLOY_URL}"
fi
write_env DEPLOY_URL "$DEPLOY_URL"

# ── Stage 6: Mise à jour de tenants.json ────────────────────────────────────
stage "Mise à jour de tenants.json"
say "On remplace le domaine d'amorçage par le vrai domaine de déploiement."
DEPLOY_HOST="${DEPLOY_URL#https://}"
DEPLOY_HOST="${DEPLOY_HOST%/}"
step "Remplacement de la clé REPLACE_WITH_YOUR_VERCEL_TEST_DOMAIN par ${DEPLOY_HOST} dans tenants.json..."
sed -i.bak "s/REPLACE_WITH_YOUR_VERCEL_TEST_DOMAIN/${DEPLOY_HOST}/" tenants.json && rm -f tenants.json.bak
write_env DEPLOY_HOST "$DEPLOY_HOST"
note "tenants.json mis à jour localement — pense à le committer (dernière étape de ce wizard)."

# ── Stage 7: Redéploiement ──────────────────────────────────────────────────
stage "Redéploiement avec tenants.json à jour"
say "Le premier déploiement embarquait encore l'ancien tenants.json — on redéploie pour prendre en compte le vrai domaine."
vercel --prod

# ── Stage 8: Vérification /api/health ───────────────────────────────────────
stage "Vérification /api/health"
say "On vérifie que toute la chaîne (tenant → authentification Google → lecture Sheets) fonctionne réellement."
step "Requête sur https://${DEPLOY_HOST}/api/health :"
HEALTH_RESPONSE=$(curl -s "https://${DEPLOY_HOST}/api/health")
printf '  %s\n' "$HEALTH_RESPONSE"
if printf '%s' "$HEALTH_RESPONSE" | grep -q '"ok":true'; then
  note "✓ ok:true — la chaîne fonctionne, le Sheet de test a bien été lu."
elif printf '%s' "$HEALTH_RESPONSE" | grep -q '(403)'; then
  warn "Réponse ok:false avec (403) — le Sheet de test n'est probablement pas partagé avec ${GCP_SA_EMAIL} (voir Stage 3)."
else
  warn "Réponse inattendue — relis le message ci-dessus pour diagnostiquer."
fi

# ── Stage 9: Vérification que .vercelignore protège les fichiers privés ────
stage "Vérification que .vercelignore protège les fichiers privés"
say "On confirme que le déploiement n'expose PAS les fichiers privés du repo (identifiants de production, docs internes)."
CODE_DEPLOY_TARGETS=$(curl -s -o /dev/null -w "%{http_code}" "https://${DEPLOY_HOST}/deploy-targets.json")
CODE_CONTEXT=$(curl -s -o /dev/null -w "%{http_code}" "https://${DEPLOY_HOST}/context.md")
note "deploy-targets.json → ${CODE_DEPLOY_TARGETS} (doit être 404)"
note "context.md → ${CODE_CONTEXT} (doit être 404)"
if [[ "$CODE_DEPLOY_TARGETS" != "404" || "$CODE_CONTEXT" != "404" ]]; then
  warn "ALERTE : un fichier privé répond avec un code différent de 404 — il est exposé publiquement !"
  warn "Ne continue PAS avant d'avoir corrigé .vercelignore et redéployé (vercel --prod)."
else
  note "✓ Les fichiers privés ne sont pas exposés."
fi

# ── Stage 10: Rappel avant de committer ─────────────────────────────────────
stage "Dernier rappel avant de committer"
say "Seul tenants.json (mis à jour) doit être committé depuis ce wizard."
warn "Ne JAMAIS committer : le fichier JSON de la clé de compte de service, un .env local, ou tout fichier contenant GOOGLE_SERVICE_ACCOUNT_KEY."
step "git add tenants.json && git commit -m \"chore(vercel): set real test-domain tenant\" — à faire toi-même (ou redemande à Claude de le faire)."
note "URL finale du déploiement de test : https://${DEPLOY_HOST}"

finish
